[workspace]
members = [
    "bin/cli",
    "bin/client",
    "bin/node",
    "bin/runtime",
    "faucet/client",
    "faucet/pallet",
    "identity/client",
    "identity/pallet",
    "identity/utils",
    "client-ffi", # move it to identity/ffi
    "keystore",

]
