[workspace]
members = [
    "bin/cli",
    "bin/client",
    "bin/node",
    "bin/runtime",
    "core",
    "faucet/cli",
    "faucet/client",
    "faucet/pallet",
    "identity/cli",
    "identity/client",
    "identity/ffi",
    "identity/pallet",
    "identity/utils",
    "keystore/keybase",
    "keystore/substrate",
    "ffi-utils",
]
