[package]
name = "ffi-identity"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[lib]
name = "libidentity"
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
cbindgen = "0.14.0"
dart-bindgen = "0.1"

[dependencies]
allo-isolate = "0.1.2"
async-std = { version = "=1.5.0", features = ["attributes"] }
client = { path = "../client", package = "client-identity" }
ffi_helpers = "0.1.0"
ipfs-embed = "0.1.1"
keystore = { path = "../../keystore", package = "keybase-keystore" }
lazy_static = "1.4"
substrate-subxt = "0.9.0"
test-client = { path = "../../bin/client" }
utils = { path = "../utils", package = "utils-identity" }
