[package]
name = "sunshine-identity-ffi"
version = "0.1.3"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"
description = "FFI for the identity module."
license = "ISC"
documentation = "https://docs.rs/sunshine-identity-ffi"
repository = "https://github.com/sunshine-protocol/sunshine-identity"

[dependencies]
allo-isolate = "0.1.2"
async-std = { version = "=1.5.0", features = ["attributes"] }
client = { version = "0.1.0", path = "../client", package = "sunshine-identity-client" }
ffi_helpers = "0.2.0"
ipfs-embed = "0.1.1"
keystore = { version = "0.1.0", path = "../../keystore", package = "keybase-keystore" }
substrate-subxt = "0.10.0"
utils = { version = "0.1.0", path = "../utils", package = "sunshine-identity-utils" }
log = "^0.4"
faucet-client = { version = "0.1.0", path = "../../faucet/client", package = "sunshine-faucet-client", optional = true }

[dev-dependencies]
test-client = { path = "../../bin/client" }


[features]
default = []
faucet = ["faucet-client"]
