[package]
name = "ffi-identity"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[dependencies]
allo-isolate = "0.1.2"
async-std = { version = "=1.5.0", features = ["attributes"] }
client = { path = "../client", package = "client-identity" }
ffi_helpers = "0.2.0"
ipfs-embed = "0.1.1"
keystore = { path = "../../keystore", package = "keybase-keystore" }
substrate-subxt = "0.9.0"
utils = { path = "../utils", package = "utils-identity" }

[dev-dependencies]
test-client = { path = "../../bin/client" }
