[package]
name = "test-client"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[features]
light = [
    "sc-service",
    "sled",
    "sp-database",
    "substrate-subxt/client",
    "test-node",
    "thiserror",
]
mock = [
    "env_logger",
    "jsonrpsee",
    "sp-keyring",
    "tempdir",
    "test-node",
]

[dependencies]
client-faucet = { path = "../../faucet/client" }
client-identity = { path = "../../identity/client" }
sled = { version = "0.32.0", optional = true }
sc-service = { version = "0.8.0-rc4", optional = true }
sp-database = { version = "2.0.0-rc4", optional = true }
substrate-subxt = { version = "0.10.1", features = ["client"] }
thiserror = { version = "1.0.20", optional = true }
utils-identity = { path = "../../identity/utils" }

env_logger = { version = "0.7.1", optional = true }
jsonrpsee = { version = "0.1.0", optional = true }
sp-keyring = { version = "2.0.0-rc4", optional = true }
tempdir = { version = "0.3.7", optional = true }
test-node = { path = "../node", optional = true }
